#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : libplacebo
Version  : 5.229.1
Release  : 26
URL      : https://github.com/haasn/libplacebo/archive/v5.229.1/libplacebo-5.229.1.tar.gz
Source0  : https://github.com/haasn/libplacebo/archive/v5.229.1/libplacebo-5.229.1.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : CC0-1.0 LGPL-2.1 LGPL-2.1+
BuildRequires : SDL2-dev
BuildRequires : SDL2_image-dev
BuildRequires : SPIRV-Tools-dev
BuildRequires : Vulkan-Headers-dev
BuildRequires : Vulkan-Loader-dev
BuildRequires : buildreq-meson
BuildRequires : glslang-dev
BuildRequires : lcms2-dev
BuildRequires : llvm-dev
BuildRequires : pypi(mako)
Patch1: 0001-Remove-static-libs-that-should-be-part-of-the-shared.patch

%description
# libplacebo
[![gitlab-ci badge](https://code.videolan.org/videolan/libplacebo/badges/master/pipeline.svg)](https://code.videolan.org/videolan/libplacebo/pipelines)
[![gitlab-ci coverage](https://code.videolan.org/videolan/libplacebo/badges/master/coverage.svg)](https://code.videolan.org/videolan/libplacebo/-/jobs/artifacts/master/file/coverage/index.html?job=test-gpu)
[![Backers on Open Collective](https://opencollective.com/libplacebo/backers/badge.svg)](#backers)
[![Sponsors on Open Collective](https://opencollective.com/libplacebo/sponsors/badge.svg)](#sponsors)
[![PayPal](https://img.shields.io/badge/donate-PayPal-blue.svg?logo=paypal)](https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=SFJUTMPSZEAHC)
[![Patreon](https://img.shields.io/badge/pledge-Patreon-red.svg?logo=patreon)](https://www.patreon.com/haasn)

%prep
%setup -q -n libplacebo-5.229.1
cd %{_builddir}/libplacebo-5.229.1
%patch1 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1672180720
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=auto "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=auto "
CFLAGS="$CFLAGS" CXXFLAGS="$CXXFLAGS" LDFLAGS="$LDFLAGS" meson --libdir=lib64 --prefix=/usr --buildtype=plain -Dvulkan=enabled \
-Dglslang=enabled \
-Dshaderc=disabled \
-Dcpp_args=-I/usr/include/glslang  builddir
ninja -v -C builddir

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
meson test -C builddir --print-errorlogs

%install
mkdir -p %{buildroot}/usr/share/package-licenses/libplacebo
cp %{_builddir}/libplacebo-%{version}/LICENSE %{buildroot}/usr/share/package-licenses/libplacebo/7fab4cd4eb7f499d60fe183607f046484acd6e2d
cp %{_builddir}/libplacebo-%{version}/demos/LICENSE %{buildroot}/usr/share/package-licenses/libplacebo/82da472f6d00dc5f0a651f33ebb320aa9c7b08d0
DESTDIR=%{buildroot} ninja -C builddir install

%files
%defattr(-,root,root,-)
